### PR TITLE
Added: flexbox Grid

### LINKED ISSUE #7: flexbox-grid ?
New repo, new lib : flexbox grid ?

### PR DESCRIPTION
**Pull request by magsout**
Close #7 

Juste two things:
- ~~about `README.md`? I don't know how to make a clear README about two way to build grid~~
- ~~about npm run script (two file, so ?)~~

### CODE REVIEW

**Comment by MoOx** [comment]
We should add at the top a clear section about the index/flex thing.

For npm script

```
"preprocess": "cssnext index.css build/index.css && cssnext flexcss build/flex.css",
```
?

**Comment by MoOx** [comment]
Otherwise it look good !

**Comment by bloodyowl** [comment]
we need to find an elegant way to let the user configure at least, given a certain viewport:

### grid

- wrap
- direction
- justification
- children alignment

### cell

- grow
- shrik
- basis
- self-alignment

**Comment by magsout** [comment]
>For npm script
"preprocess": "cssnext index.css build/index.css && cssnext flexcss build/flex.css",
?

Done

**Comment by magsout** [comment]
Any idea @bloodyowl ?

**Comment by MoOx** [comment]
Please add a note in the readme about the flex version. Then we can push this :)
We should create new issues for other enhancements.

**Comment by magsout** [comment]
Juste add a note (@MoOx) README.md.

**Comment by MoOx** [comment]
:+1:

**Comment by MoOx** [comment]
1.0 is out :)

**Comment by magsout** [comment]
:+1: coool.

**Comment by MoOx** [comment]
Thanks btw :)

**Comment by bloodyowl** [comment]
no modifiers? :/

**Comment by MoOx** [comment]
https://github.com/cssrecipes/grid/issues/10

**Pull request merged**
